name: Feature Request
description: Suggest a new feature or improvement for AgentIM
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature. Please describe your idea below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the feature you'd like.
      placeholder: What would you like to see?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Use Case / Motivation
      description: Why is this feature needed? What problem does it solve?
      placeholder: Describe the use case or pain point this would address.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: If you have an idea for how this could be implemented, describe it here.
    validations:
      required: false

  - type: dropdown
    id: package
    attributes:
      label: Affected Package
      description: Which package would this feature belong to?
      options:
        - shared
        - server
        - gateway
        - web
        - multiple
        - unsure
    validations:
      required: true
