#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

ENV_FILE=".env"

# Generate a random password (URL-safe, 24 characters)
generate_password() {
  openssl rand -base64 24 | tr '+/' '-_' | head -c 24
}

if [ -f "$ENV_FILE" ]; then
  echo "Found existing $ENV_FILE — using current configuration."
else
  echo "No $ENV_FILE found — generating one with random secrets..."

  PORT="${PORT:-3000}"
  JWT_SECRET=$(openssl rand -hex 32)
  ENCRYPTION_KEY=$(openssl rand -hex 32)
  POSTGRES_PASSWORD=$(openssl rand -base64 16)
  ADMIN_PASSWORD=$(generate_password)

  cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
JWT_SECRET=${JWT_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ADMIN_USERNAME=admin
ADMIN_PASSWORD=${ADMIN_PASSWORD}
PORT=${PORT}
CORS_ORIGIN=http://localhost:${PORT}
JWT_ACCESS_EXPIRY=15m
JWT_REFRESH_EXPIRY=7d
EOF

  echo ""
  echo "=========================================="
  echo "  AgentIM — Generated Credentials"
  echo "=========================================="
  echo "  Admin Username : admin"
  echo "  Admin Password : ${ADMIN_PASSWORD}"
  echo "  Port           : ${PORT}"
  echo "=========================================="
  echo "  Save these credentials! They are stored"
  echo "  in docker/.env for reference."
  echo "=========================================="
  echo ""
fi

echo "Starting AgentIM with Docker Compose..."
docker compose up -d --build

echo ""
echo "AgentIM is starting up. Access it at:"
# shellcheck disable=SC1091
source "$ENV_FILE" 2>/dev/null || true
echo "  http://localhost:${PORT:-3000}"
echo ""
echo "View logs:  docker compose logs -f"
echo "Stop:       docker compose down"
